# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=200)),
                ('log_level', models.IntegerField(choices=[(1, 'DEBUG'), (2, 'INFO'), (3, 'WARNING'), (4, 'ERROR')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LogAdditionalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_logger_app.Log')),
            ],
        ),
        migrations.CreateModel(
            name='LogReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=200)),
                ('key', models.IntegerField(choices=[(1, 'LOG_LEVEL'), (2, 'MESSAGE_PREFIX')], default=1)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
