# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_logger_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logadditionaldata',
            name='log_id',
        ),
        migrations.DeleteModel(
            name='LogAdditionalData',
        ),
    ]
