# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_logger_app', '0003_auto_20160211_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.TextField(default='debug info'),
            preserve_default=False,
        ),
    ]
