# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_logger_app', '0004_log_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_level',
            field=models.IntegerField(choices=[(1, 'DEBUG'), (2, 'INFO'), (3, 'WARNING'), (4, 'ERROR')]),
        ),
    ]
